import Head from "next/head";
import Navbar from "@/components/Navbar";
import { useCallback, useEffect, useState } from "react";
import EateriesSearch from "@/components/EateriesSearch";
import axios from "axios";
import DisplayEateries from "@/components/DisplayEateries";

export default function Eateries() {
  const [searchTerm, setSearchTerm] = useState("");
  const [location, setLocation] = useState("");
  const [results, setResults] = useState([]);
  // add a sort by param!

  const searchApi = useCallback(() => {
    axios
      .get(
        `https://cors-anywhere.herokuapp.com/https://api.yelp.com/v3/businesses/search`,
        {
          headers: {
            Authorization:
              "Bearer GMdgqZxxz0Fym_V-b_gV8-_tFuNUumyuqKKQXik5Agk6GSdywFJ2gICxCHC2FQ2ZvW69317VGQLYNJy0CeBU_jn9S9oUTuaYODm3ZjwAh8JKsYkfovRK_z87_jPeZHYx",
          },
          params: {
            term: searchTerm,
            location: location,
            limit: 20,
          },
        }
      )
      .then((res) => {
        setResults(res.data.businesses);
      })
      .catch(() => {
        console.log("error");
      });
  }, [location, searchTerm]);

  useEffect(() => {
    searchApi;
  }, [searchApi, searchTerm]);

  const styles = {
    outerContainer: {
      display: "flex",
      justifyContent: "center",
      flexDirection: "column",
      alignItems: "center",
    },
    container: {
      display: "flex",
      width: "90%",
      flexDirection: "column" as "column",
      alignItems: "center",
    },
    title: {
      fontSize: 40,
      width: "100%",
    },
  };

  return (
    <>
      <Head>
        <title>Stamp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/stamp.png" />
      </Head>
      <Navbar />
      <div style={styles.outerContainer}>
        <div style={styles.container}>
          <p style={styles.title}>Eateries</p>
          <EateriesSearch
            searchTerm={searchTerm}
            setSearchTerm={setSearchTerm}
            location={location}
            setLocation={setLocation}
            onSubmit={searchApi}
          />
          <DisplayEateries results={results} setSearchTerm={setSearchTerm} />
        </div>
      </div>
    </>
  );
}
