import Head from "next/head";
import React, { useState } from "react";
import Navbar from "@/components/Navbar";
import { DateRange } from "@mui/x-date-pickers-pro/DateRangePicker";
import { Moment } from "moment";
import FlightSearch from "@/components/EateriesSearch";

export default function Flights() {
  // should edit the options every time from, to, and date is changed
  const [dates, setDates] = useState<DateRange<Moment>>([null, null]);
  const [from, setFrom] = useState("");
  const [to, setTo] = useState("");

  // want to send a new request every time the button is pressed
  // this should be in the function that is put into the `onPress` function for the search button

  const axios = require("axios");

  const options = {
    method: "GET",
    url: "https://travelpayouts-travelpayouts-flight-data-v1.p.rapidapi.com/v1/prices/direct/",
    params: { destination: "ICN", origin: "JFK" },
    headers: {
      "X-Access-Token": "cafa18ea26aba33fc3b03aa167ecb09c",
      "X-RapidAPI-Key": "b16dada281mshcbcbf5d7a78053bp13b90ejsnb748d0659a0e",
      "X-RapidAPI-Host":
        "travelpayouts-travelpayouts-flight-data-v1.p.rapidapi.com",
    },
  };

  // probably put this in the onPress
  axios
    .request(options)
    .then(function (response) {
      // set response.data to a variable that I can pull information from
      console.log(response.data);
    })
    .catch(function (error) {
      console.error(error);
    });

  const styles = {
    width: {
      display: "flex",
      justifyContent: "center",
    },
    container: {
      width: "90%",
      display: "flex",
      paddingTop: "3%",
      justifyContent: "center",
    },
    middle: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
    },
    title: {
      color: "#557A95",
      fontSize: 48,
    },
    suitcases: {
      maxWidth: 500,
      maxHeight: 640,
      marginTop: 50,
    },
    input: {
      fontFamily: "Optima, serif",
      fontSize: 20,
      marginRight: "1%",
    },
    dateInput: {
      fontFamily: "Optima, serif",
    },
    dateInputContainer: {
      border: "none",
    },
  };
  return (
    <>
      <Head>
        <title>Stamp - Flights</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div style={styles.width}>
        <div style={styles.container}>
          <FlightSearch
            dates={dates}
            setDates={setDates}
            from={from}
            to={to}
            setFrom={setFrom}
            setTo={setTo}
          />
        </div>
      </div>
    </>
  );
}
