import Head from "next/head";
import React, { useState } from "react";
import Navbar from "@/components/Navbar";
import Image from "next/image";
import Paper from "@mui/material/Paper";
import InputBase from "@mui/material/InputBase";
import FlightTakeoffIcon from "@mui/icons-material/FlightTakeoff";
import FlightLandIcon from "@mui/icons-material/FlightLand";
import { TextField, Box } from "@mui/material";
import { LocalizationProvider } from "@mui/x-date-pickers-pro";
import { AdapterMoment } from "@mui/x-date-pickers-pro/AdapterMoment";
import { DesktopDateRangePicker } from "@mui/x-date-pickers-pro/DesktopDateRangePicker";
import { DateRange } from "@mui/x-date-pickers-pro/DateRangePicker";
import { Moment } from "moment";
import InputAdornment from "@mui/material/InputAdornment";
import Button from "@mui/material/Button";
import DateRangeIcon from "@mui/icons-material/DateRange";
import PersonIcon from "@mui/icons-material/Person";
import IconButton from "@mui/material/IconButton";
import SearchIcon from "@mui/icons-material/Search";

export default function Flights() {
  const [value, setValue] = useState<DateRange<Moment>>([null, null]);

  const styles = {
    width: {
      display: "flex",
      justifyContent: "center",
    },
    container: {
      width: "80%",
      display: "flex",
      paddingTop: "3%",
    },
    middle: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
    },
    title: {
      color: "#557A95",
      fontSize: 48,
    },
    suitcases: {
      maxWidth: 500,
      maxHeight: 640,
      marginTop: 50,
    },
    input: {
      fontFamily: "Optima, serif",
      fontSize: 20,
      marginRight: "1%",
    },
    dateInput: {
      fontFamily: "Optima, serif",
    },
    dateInputContainer: {
      border: "none",
    },
  };
  return (
    <>
      <Head>
        <title>Stamp - Flights</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div style={styles.width}>
        <div style={styles.container}>
          <Paper
            elevation={7}
            sx={{
              display: "flex",
              alignItems: "center",
              marginBottom: 20,
              padding: "10px",
              marginTop: "10%",
            }}
          >
            <FlightTakeoffIcon style={{ margin: 10, color: "gray" }} />
            <InputBase placeholder="From" style={styles.input}></InputBase>
            <FlightLandIcon style={{ margin: 10, color: "gray" }} />
            <InputBase placeholder="To" style={styles.input}></InputBase>
            <DateRangeIcon style={{ margin: 10, color: "gray" }} />
            <LocalizationProvider
              dateAdapter={AdapterMoment}
              localeText={{ start: "Depart", end: "Return" }}
            >
              <DesktopDateRangePicker
                value={value}
                onChange={(newValue) => {
                  setValue(newValue);
                }}
                renderInput={(startProps, endProps) => (
                  <React.Fragment>
                    <TextField
                      {...startProps}
                      InputLabelProps={{ style: styles.dateInput }}
                      variant="standard"
                    />
                    <Box sx={{ mx: 2 }}>
                      <p style={styles.input}>-</p>
                    </Box>
                    <TextField
                      {...endProps}
                      InputLabelProps={{ style: styles.dateInput }}
                      variant="standard"
                    />
                  </React.Fragment>
                )}
              />
            </LocalizationProvider>
            <PersonIcon style={{ margin: 10, color: "gray" }} />
            <TextField
              type="number"
              defaultValue={1}
              InputProps={{
                endAdornment: (
                  <InputAdornment position="end">
                    <p style={styles.dateInput}>Adults</p>
                  </InputAdornment>
                ),
              }}
              variant="standard"
              label="Travelers"
              sx={{ width: 100, paddingRight: "3%" }}
              InputLabelProps={{ style: styles.dateInput }}
            />
            <IconButton
              size="medium"
              sx={{
                backgroundColor: "#557A95",
                color: "white",
                marginRight: "1%",
              }}
            >
              <SearchIcon fontSize="inherit" />
            </IconButton>
          </Paper>
        </div>
      </div>
    </>
  );
}
