import Head from "next/head";
import React, { useState } from "react";
import Navbar from "@/components/Navbar";
import Image from "next/image";

export default function Flights() {
  const styles = {
    container: {
      width: "80%",
    },
    middle: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
    },
    centerText: {
      color: "#557A95",
      fontSize: 80,
    },
    suitcases: {
      maxWidth: 500,
      maxHeight: 640,
      marginTop: 50,
    },
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div style={styles.container}>
        <p style={styles.centerText}>Flights</p>
      </div>
    </>
  );
}
