import Head from "next/head";
import Navbar from "@/components/Navbar";
import { collection, query, onSnapshot } from "firebase/firestore";
import { db } from "../util/firebase";
import { useEffect, useState } from "react";
import DisplayItineraries from "@/components/DisplayItineraries";
import { idList } from "@/types/types";
import { Button } from "@mui/material";
import AddIcon from "@mui/icons-material/Add";
import AddNewItinerary from "@/components/AddNewItinerary";

export default function Itineraries() {
  const itinerariesCollectionRef = collection(db, "itineraries");
  const itinerariesQuery = query(itinerariesCollectionRef);

  const [itineraries, setItineraries] = useState<idList>([]);

  useEffect(() => {
    const unsubscribe = onSnapshot(itinerariesQuery, (querySnapshot) => {
      const idList: idList = [];
      querySnapshot.docs.map((x) => {
        const obj = {
          location: x.get("location"),
          eateries: x.get("eateries"),
          sights: x.get("sights"),
          image: x.get("image"),
          dates: x.get("dates"),
        };
        const newObj = { ...obj, id: x.id };
        idList.push(newObj);
      });
      setItineraries(idList);
    });
    return unsubscribe;
  }, []);

  const [open, setOpen] = useState(false);

  const handleClickOpen = () => {
    setOpen(true);
  };

  const handleClose = () => {
    setOpen(false);
  };

  const styles = {
    outerContainer: {
      display: "flex",
      justifyContent: "center",
    },
    container: {
      display: "flex",
      width: "90%",
      flexDirection: "column" as "column",
      alignItems: "center",
    },
    title: {
      fontSize: 40,
      width: "100%",
    },
    top: {
      display: "flex",
      width: "100%",
      justifyContent: "space-between",
    },
  };

  return (
    <>
      <Head>
        <title>Stamp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/stamp.png" />
      </Head>
      <Navbar />

      <div style={styles.outerContainer}>
        <div style={styles.container}>
          <div style={styles.top}>
            <p style={styles.title}>Your Itineraries</p>
            <Button
              endIcon={<AddIcon style={{ color: "white" }} />}
              onClick={handleClickOpen}
              sx={{
                width: "20%",
                borderRadius: 50,
                backgroundColor: "#557A95",
              }}
            >
              <p style={{ color: "white" }}>Add New Itinerary</p>
            </Button>
          </div>

          <DisplayItineraries
            itineraries={itineraries}
            collection={itinerariesCollectionRef}
          />
        </div>
      </div>

      <AddNewItinerary
        open={open}
        setOpen={setOpen}
        handleClose={handleClose}
        collection={itinerariesCollectionRef}
      />
    </>
  );
}
