import Head from "next/head";
import Navbar from "@/components/Navbar";
import { collection, query, onSnapshot } from "firebase/firestore";
import { db } from "../util/firebase";
import { useEffect, useState } from "react";
import DisplayItineraries from "@/components/DisplayItineraries";
import { idList } from "@/types/types";

export default function Itineraries() {
  const itinerariesCollectionRef = collection(db, "itineraries");
  const itinerariesQuery = query(itinerariesCollectionRef);

  const [itineraries, setItineraries] = useState<idList>([]);

  useEffect(() => {
    const unsubscribe = onSnapshot(itinerariesQuery, (querySnapshot) => {
      const idList: idList = [];
      querySnapshot.docs.map((x) => {
        const obj = {
          location: x.get("location"),
          eateries: x.get("eateries"),
          sights: x.get("sights"),
          image: x.get("image"),
          dates: x.get("dates"),
        };
        const newObj = { ...obj, id: x.id };
        idList.push(newObj);
      });
      setItineraries(idList);
    });
    return unsubscribe;
  }, []);

  const styles = {
    outerContainer: {
      display: "flex",
      justifyContent: "center",
    },
    container: {
      display: "flex",
      width: "90%",
      flexDirection: "column" as "column",
      alignItems: "center",
    },
    title: {
      fontSize: 40,
      width: "100%",
    },
  };

  return (
    <>
      <Head>
        <title>Stamp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <div style={styles.outerContainer}>
        <div style={styles.container}>
          <p style={styles.title}>Your Itineraries</p>
          <DisplayItineraries itineraries={itineraries} />
        </div>
      </div>
    </>
  );
}
