import Head from "next/head";
import Navbar from "@/components/Navbar";
import SightsSearch from "@/components/SightsSearch";
import DisplaySights from "@/components/DisplaySights";
import { useState } from "react";
import axios from "axios";

export default function Sights() {
  const [location, setLocation] = useState("");
  const [results, setResults] = useState([]);

  const searchApi = () => {
    axios
      .get(
        `https://cors-anywhere.herokuapp.com/https://api.yelp.com/v3/businesses/search`,
        {
          headers: {
            Authorization:
              "Bearer GMdgqZxxz0Fym_V-b_gV8-_tFuNUumyuqKKQXik5Agk6GSdywFJ2gICxCHC2FQ2ZvW69317VGQLYNJy0CeBU_jn9S9oUTuaYODm3ZjwAh8JKsYkfovRK_z87_jPeZHYx",
          },
          params: {
            term: "tourist attractions",
            location: location,
            limit: 20,
            sort_by: "review_count",
          },
        }
      )
      .then((res) => {
        setResults(res.data.businesses);
      })
      .catch((err) => {
        console.log("error");
      });
  };

  const styles = {
    outerContainer: {
      display: "flex",
      justifyContent: "center",
    },
    container: {
      display: "flex",
      width: "90%",
      flexDirection: "column" as "column",
      alignItems: "center",
    },
    title: {
      fontSize: 40,
      width: "100%",
    },
  };

  return (
    <>
      <Head>
        <title>Stamp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/stamp.png" />
      </Head>
      <Navbar />

      <div style={styles.outerContainer}>
        <div style={styles.container}>
          <p style={styles.title}>Sights</p>
          <SightsSearch
            location={location}
            setLocation={setLocation}
            onSubmit={searchApi}
          />
          <DisplaySights results={results} />
        </div>
      </div>
    </>
  );
}
